
<!doctype html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="msapplication-tap-highlight" content="no"/>

    <link rel="icon" type="image/png" href="assets/img/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="assets/img/favicon-32x32.png" sizes="32x32">

    <title>Altair Admin v2.13.0</title>


    <!-- uikit -->
    <link rel="stylesheet" href="bower_components/uikit/css/uikit.almost-flat.min.css" media="all">

    <!-- flag icons -->
    <link rel="stylesheet" href="assets/icons/flags/flags.min.css" media="all">

    <!-- style switcher -->
    <link rel="stylesheet" href="assets/css/style_switcher.min.css" media="all">
    
    <!-- altair admin -->
    <link rel="stylesheet" href="assets/css/main.min.css" media="all">

    <!-- themes -->
    <link rel="stylesheet" href="assets/css/themes/themes_combined.min.css" media="all">
    <link rel="stylesheet" type="text/css" href="vendors/font-awesome/css/font-awesome.min.css">
</head>
<body >
    <?php include 'blog_navs.php'; ?>
        <div id="page_content">
        <div id="page_content_inner">

            <div class="uk-width-medium-8-10 uk-container-center">

                <div class="md-card md-card-single">
                    <div class="md-card-toolbar">
                        <div class="md-card-toolbar-actions">
                            <i class="md-icon material-icons" id="toggleAll">&#xe8f2;</i>
                        </div>
                        <h3 class="md-card-toolbar-heading-text large">
                            Help Center
                        </h3>
                    </div>
                    <div class="md-card-content padding-reset">
                        <h4 class="heading_c full_width_in_card">First Section</h4>
                        <div class="uk-accordion uk-accordion-alt hierarchical_slide help_accordion" data-slide-children="h3" data-slide-context=".md-card-content">
                            <h3 class="uk-accordion-title">Enim est et animi aut provident non in sunt iure.</h3>
                            <div class="uk-accordion-content">
                                <p>Suscipit in est occaecati qui et omnis neque sed placeat sed velit sit eveniet voluptatem similique quisquam odit incidunt qui et quidem ipsam id assumenda sint inventore dolor quo tempora voluptatum qui eligendi quia et earum sint deserunt quibusdam dolor non in illo esse ad dolorem est aut illum officiis tempora accusamus sed odit quasi eos qui ea dolore voluptatum perspiciatis quibusdam et ut eius aliquam unde fugiat omnis sed qui ipsam numquam in distinctio quia minus harum sed vel voluptatem nesciunt nisi cum praesentium consequuntur temporibus repudiandae cum quidem enim voluptas minus aliquam a qui et fugit dolorem modi debitis consequuntur et expedita mollitia autem debitis nobis ullam neque vel non reprehenderit quas architecto eius perspiciatis atque debitis est rem enim veritatis soluta qui id harum quasi voluptates sapiente iusto inventore et consequatur est qui id aut non at reiciendis repellat quo possimus quo molestias eligendi dolores adipisci vel dicta suscipit qui qui tenetur corrupti voluptatem assumenda occaecati quod temporibus sed autem ullam aut molestias omnis laborum cum totam consequatur eum voluptates asperiores autem expedita cupiditate.</p>
                            </div>
                            <h3 class="uk-accordion-title">Quam nobis laudantium est officia earum animi.</h3>
                            <div class="uk-accordion-content">
                                <p>Numquam impedit ducimus aut qui provident sit voluptatem soluta voluptatem dolor suscipit earum autem aperiam excepturi dignissimos quia eum consectetur occaecati esse ad mollitia aut voluptate eligendi dolores consequuntur amet ipsam similique vel est qui voluptatum voluptates voluptatem commodi aut blanditiis aliquid atque est voluptatem nostrum blanditiis voluptatem ratione ut maiores et voluptatem fugiat aspernatur aut quibusdam omnis et enim occaecati ducimus dicta ab excepturi ea vel est fugit quae nulla culpa quam et deleniti ipsa nemo consectetur vitae rem sapiente repellendus architecto adipisci in excepturi ut ea corporis voluptatem earum omnis amet mollitia ipsa dolores cupiditate voluptatem error voluptatum voluptatem dolores aliquam corrupti reiciendis et qui cum in pariatur at porro id non id consequatur minus nulla incidunt nostrum rem perferendis laudantium ratione ut rem atque enim labore voluptatem nihil et pariatur quis non similique et et cupiditate expedita voluptates modi soluta consequatur perferendis in corporis illo dolore atque aut autem quod aliquid maiores veritatis dolores dolores nihil praesentium labore distinctio et culpa et error dolores aliquid earum earum quo totam rerum culpa asperiores repellat aperiam eaque sit dolores odio ipsum dolore aliquam vel quo mollitia odit dolores est aut necessitatibus porro distinctio voluptatem vel et quas et earum eligendi libero laborum assumenda officiis.</p>
                            </div>
                            <h3 class="uk-accordion-title">Molestias et neque quaerat eos corporis recusandae dolor quis voluptas consequatur odio.</h3>
                            <div class="uk-accordion-content">
                                <p>Placeat enim quo velit placeat ut alias qui numquam dolorem quibusdam ducimus excepturi officiis voluptatem ratione quis et dolor labore tempore nisi et qui voluptatibus in rerum vel minima culpa aut enim consequatur incidunt ipsam placeat culpa in ut quis rerum eligendi dolorem et et at voluptatem corporis sequi qui cum architecto quae ex harum aut quisquam deserunt omnis sit ullam sint consequatur qui molestiae ut ex explicabo sed rerum id necessitatibus qui non eum velit odit qui qui quia saepe ex magnam cum deserunt provident accusamus iure laudantium magnam hic sint vitae excepturi laborum deserunt voluptatem architecto illum et voluptatum optio fugiat harum et sunt inventore eum quo et quaerat voluptas esse minus repellat non odit rem recusandae sapiente qui beatae dolor explicabo veniam sapiente in et deleniti corrupti et autem itaque dolores numquam ea est quo sed eos dolorem rerum laboriosam distinctio expedita tempore fugit blanditiis quibusdam fugit a et recusandae delectus dolorem non delectus.</p>
                            </div>
                            <h3 class="uk-accordion-title">Asperiores corporis voluptatem labore animi eveniet nostrum suscipit pariatur ea dolores.</h3>
                            <div class="uk-accordion-content">
                                <p>Non inventore recusandae maiores ut ea sit laboriosam doloribus ut qui natus dolores et ullam minus dolores itaque voluptas delectus harum doloribus dolorum ut similique quas ipsa recusandae est laborum sit blanditiis occaecati omnis deserunt iste nisi earum et omnis maxime quam omnis laudantium vel quis voluptatem quaerat eum quod numquam distinctio voluptatem fuga unde minus omnis velit distinctio id sit molestiae in et voluptate at et quo quis autem neque ut sapiente eveniet beatae dignissimos eum consectetur repellat accusantium possimus sunt quidem nemo eum odio voluptates minus dolor quia ducimus repellat suscipit quos libero repudiandae ut voluptas dolorem aut ut cumque eos recusandae veniam pariatur quod eum repellendus architecto sunt quo dolorem minima dicta vel quibusdam aut quia aut doloribus non consequuntur repellendus quas dicta et id quam magni enim atque eligendi eius enim et quam ut ducimus cupiditate ut iusto id et debitis ex dolorem deserunt nostrum impedit laborum veniam consequatur accusamus omnis hic possimus inventore vel possimus ut est hic dolores necessitatibus accusantium minus explicabo repudiandae possimus ut eum similique commodi et aut odio quis modi commodi expedita assumenda nulla porro culpa et quaerat consequatur et nulla eaque exercitationem dolore voluptas quia sit illum dolores ea natus recusandae maxime voluptatem consequuntur quo qui et minus quidem sunt est id eos et voluptatem ipsum doloribus quia in nihil consequatur quaerat aliquam quia non est expedita placeat totam maxime eos praesentium dolorum velit dolore laboriosam occaecati fuga omnis alias aut quisquam cupiditate voluptas voluptatem eaque aliquam illo fugiat.</p>
                            </div>
                            <h3 class="uk-accordion-title">Iusto nostrum aspernatur quis perferendis omnis magnam nemo nihil aliquid dolore minima aut aut.</h3>
                            <div class="uk-accordion-content">
                                <p>Minus voluptatibus ab quia earum qui alias nisi nam doloribus est voluptatem nisi quidem asperiores et architecto consectetur autem quibusdam aliquam quo corrupti illo quis ipsam at debitis nihil fugiat perspiciatis voluptatem voluptatem qui sed sint earum sunt omnis doloribus sed et et mollitia qui illum veniam perferendis veniam in repudiandae occaecati quia quaerat odio non et expedita recusandae voluptas sint ut provident nisi voluptatum sapiente non est incidunt quo aliquam reiciendis deserunt consequatur saepe ab quae enim sequi aut eaque sed consectetur et libero assumenda consequatur sint quo aut totam officiis accusantium et officia sint quos dicta non alias ad libero non quia harum modi saepe nulla deleniti odit iure ab quo reprehenderit eveniet qui incidunt quisquam quae et est quae eligendi suscipit fugiat voluptas suscipit nam ut facere consectetur sit doloribus aut doloremque voluptatibus eaque dolorum dignissimos amet aspernatur dignissimos iure quo doloribus quasi consequatur excepturi laborum laborum et aut odio dolorum nihil eveniet incidunt accusantium et explicabo quos enim quam voluptatem ut necessitatibus occaecati nesciunt quis cupiditate qui optio et omnis quia modi qui enim commodi est dolor neque nemo enim consequuntur et vel a nam commodi fugiat et soluta vero eos itaque et aut facilis nihil totam assumenda qui.</p>
                            </div>
                            <h3 class="uk-accordion-title">Eius hic ut molestiae occaecati fuga quidem aut aut maxime voluptates voluptatibus.</h3>
                            <div class="uk-accordion-content">
                                <p>Explicabo earum quisquam et libero sapiente sint quia eaque qui voluptatem inventore quasi esse et aut aliquid ea eum vel quis animi enim aut aliquid quam ad ipsam sed ipsum at distinctio consequatur aspernatur libero quaerat laboriosam fugiat doloremque aut omnis non odit corrupti enim labore dolorum et harum sit autem inventore aut cum laboriosam quam doloribus et quo enim dolores qui eaque eum et qui recusandae harum ut delectus quis porro eaque occaecati alias ut et quam et assumenda velit hic voluptatem eveniet vero quis iusto nemo dolores harum voluptatem perspiciatis ea porro exercitationem explicabo illo minima provident beatae perferendis non assumenda beatae eum quas aut vero ipsa eum vel et consequatur et doloribus dolor distinctio atque vitae ab magnam perferendis qui tempora quae id unde eos et unde facilis minus voluptas et explicabo laboriosam est molestiae quia accusantium laborum commodi aut dolores voluptas sint ratione nam ex quia molestiae nulla libero eligendi iusto ut blanditiis velit eos soluta laboriosam dolorem et consequatur et voluptas magni labore autem nulla aut maxime ratione omnis optio temporibus qui est quo voluptatibus sit veniam fuga dolore delectus provident dolores sint harum dolor id ut libero qui alias quaerat optio sequi mollitia id repellat qui qui repudiandae accusantium nulla quae nesciunt quia illo accusamus et quibusdam recusandae corrupti sint praesentium illum praesentium occaecati quis repellat voluptate maiores ex deleniti iure odit quos eligendi voluptatum ut rem quia quis asperiores vitae saepe ut voluptates ipsa quo fuga occaecati et.</p>
                            </div>
                        </div>
                        <h4 class="heading_c full_width_in_card">Other Section</h4>
                        <div class="uk-accordion uk-accordion-alt hierarchical_slide help_accordion" data-slide-children="h3" data-slide-context=".md-card-content">
                            <h3 class="uk-accordion-title">Velit quia ipsam minima aperiam recusandae nihil magnam consequatur doloribus sit enim ut.</h3>
                            <div class="uk-accordion-content">
                                <p>Voluptas aut sequi non est nesciunt ut consequuntur delectus iste quod in reiciendis delectus et et nisi saepe hic sunt voluptas delectus commodi veritatis exercitationem sunt consequatur esse est qui magnam aliquid odio laborum aut est vel velit omnis est ducimus sunt neque sit et dolorem et voluptatibus est est nisi alias facilis cumque perferendis eius et nihil reiciendis laboriosam soluta recusandae facere illo magnam nesciunt vero accusantium quo voluptatem et perferendis sunt et nesciunt illum qui velit autem illum quia beatae odit sed accusantium voluptatem est impedit rerum voluptatem est itaque aut adipisci quibusdam quo quae culpa et reprehenderit voluptatum voluptatem aut dolores facilis et aut odio sapiente eum veritatis ipsum voluptate et officiis eligendi architecto ipsa autem consequatur ut vel rerum dolores rem quo accusamus non dolor suscipit eius quo odit architecto optio est harum sit illum omnis maxime officia voluptate voluptatibus temporibus cupiditate porro illo beatae molestiae non et quibusdam nihil et ipsum officia saepe enim excepturi ab quis facere delectus asperiores totam maiores voluptas tempora rerum sed voluptate ea sed qui voluptas magni sunt distinctio deleniti aut dignissimos hic assumenda quia dolor qui provident enim consequatur nesciunt perferendis ut expedita et et id necessitatibus magni impedit aperiam neque voluptas cupiditate consectetur quas aut asperiores nobis aut nobis minima eligendi doloremque ipsum sunt ut non aut repellat eum quia doloribus sequi officia sed velit corrupti delectus qui et laudantium voluptatem nemo sunt qui harum aliquam voluptas natus ut delectus fugiat ea qui autem ad corrupti voluptate qui eum et blanditiis magnam cumque tenetur et corrupti similique est dolor.</p>
                            </div>
                            <h3 class="uk-accordion-title">Officiis facere necessitatibus laudantium numquam ipsa sint consectetur ut molestiae enim sunt dolores.</h3>
                            <div class="uk-accordion-content">
                                <p>Id facere est eum rerum qui laboriosam alias perferendis quis ab minus commodi quos iusto quia animi voluptatem quisquam et sed voluptatem qui a officia natus corrupti non voluptates soluta reprehenderit nam aperiam fugit ad rerum rem nihil ex aut dolorem sed voluptate expedita id iste eos et repudiandae est dicta sed accusantium qui fugiat numquam porro quaerat est magni voluptatem qui perferendis commodi ipsum sequi qui quibusdam laboriosam similique quia molestias doloribus quia praesentium aut id consequatur odit provident eius repellat voluptate dolores maxime et hic inventore qui quod eligendi et provident sapiente nisi fugit et magni autem libero sed dolor aut rerum nobis cum deserunt aut molestias voluptatibus facere sequi aliquid velit in quia nobis et consequatur ut laborum facilis molestiae numquam iste quasi vero recusandae consequuntur at aliquid quam non non eaque dolores et hic voluptas iste neque sequi tenetur aliquam possimus repudiandae reiciendis debitis quo est nesciunt quos nemo libero voluptatibus doloribus voluptatem quis exercitationem dolor odio sed suscipit et incidunt natus libero ducimus et distinctio ut ex provident rem commodi et sint nostrum ex omnis qui ut eaque illo libero ut deleniti illum aperiam quas consectetur corrupti aut error aut ut qui a ipsam odit repellat in sed nam voluptatem sequi doloribus voluptatibus sequi et est.</p>
                            </div>
                            <h3 class="uk-accordion-title">Minima distinctio aut quisquam rerum explicabo quo quia odio et placeat quo.</h3>
                            <div class="uk-accordion-content">
                                <p>Aut tempora consequuntur earum nemo perspiciatis cum quibusdam asperiores ut eaque sequi officiis maxime eaque nobis necessitatibus illo libero occaecati possimus quos id nihil voluptatem sed laudantium laudantium autem et velit aspernatur eos est occaecati dicta reiciendis inventore sit vitae aut sit nostrum eum harum cum vel dolorem deserunt unde dolore tempore animi adipisci officiis aut omnis similique ut tenetur consequuntur minus ut est fuga nam cupiditate a nihil qui iure architecto explicabo voluptas recusandae quia delectus ut qui ab accusamus suscipit sit ut sint repellendus in quisquam temporibus laboriosam omnis temporibus est possimus velit odio debitis ea autem dolores quas laborum nam nulla perspiciatis nihil enim necessitatibus aut repellat nobis ullam sit quia corporis repellendus dicta ab ducimus repellendus magni magnam sunt iste suscipit est reprehenderit pariatur ratione ut quisquam tenetur in quis veniam repellat quia accusamus totam maiores voluptatem expedita sed ut porro aperiam ut est tenetur maxime et ut reprehenderit eaque quo et laborum reprehenderit atque occaecati provident quis non asperiores minus animi quos consectetur et dolorum hic consequuntur nam ut eos autem et quos nihil veritatis est ea qui vel repudiandae voluptatum qui enim et sit iusto et cupiditate repellat praesentium sapiente sit omnis molestias doloremque delectus laboriosam et.</p>
                            </div>
                            <h3 class="uk-accordion-title">Assumenda possimus rerum quos consequatur perferendis esse quam assumenda earum deleniti.</h3>
                            <div class="uk-accordion-content">
                                <p>Quasi laboriosam expedita quia eius maxime iusto nam aut sed sunt non sint aspernatur mollitia et laborum ut cumque est at numquam corporis maiores pariatur harum ut quae ut iusto occaecati quo illum veniam qui et ipsum alias animi dolor officiis corporis et maxime eius aut repellendus excepturi voluptatibus ipsum dolores pariatur vitae quidem quas sit praesentium ducimus nostrum maxime ex dignissimos nam illo repudiandae aliquid doloribus ea et ex consequuntur voluptatem est sit rerum corrupti voluptas sit molestiae quidem qui quo et magnam qui rem pariatur qui eius eos ullam veniam maxime sit odit et dignissimos sed provident pariatur dolorem omnis mollitia voluptas non quia numquam qui quasi iusto vel quam aut ut exercitationem et sit eos eos et culpa est nihil nobis voluptas eos qui sit est rerum fugiat consequatur sapiente temporibus voluptatem enim voluptatem temporibus facere quaerat esse aut et eos sit cum velit quae ut esse in aperiam odio doloribus ut dolor et doloribus autem asperiores earum voluptatem ex ipsam asperiores impedit aut et sunt saepe quia facere voluptates impedit minima qui similique porro suscipit vel adipisci ea consequatur qui voluptate ea et dolorem voluptate tenetur soluta accusamus molestiae minima magnam tempora optio dolore odio doloremque odio quae ut debitis modi omnis velit nihil veniam accusamus voluptatem voluptates earum sed tempore laboriosam officia rerum dolore labore placeat eaque suscipit dignissimos omnis rerum qui veniam aut sunt ullam quia voluptatem nisi quia et cum aut possimus id nobis dolores et aut expedita est minima.</p>
                            </div>
                            <h3 class="uk-accordion-title">Sed id quasi aut ratione beatae maxime.</h3>
                            <div class="uk-accordion-content">
                                <p>Magni illo nobis aut laborum ut voluptatem est dolore atque eos aut corrupti eos quaerat sunt amet aut sunt ipsam sint voluptas magnam delectus debitis inventore possimus autem quibusdam nam aspernatur numquam esse vero reiciendis et porro minima perspiciatis dignissimos autem maxime aliquid vel alias est exercitationem qui veniam corporis suscipit dolore ab dolorem minima voluptas dolor illum enim et magnam veniam et aspernatur sit voluptas veritatis voluptatum cupiditate fugit eius odit quis illo fugiat ratione ut id rem doloremque esse voluptatibus aut libero sapiente placeat occaecati et assumenda dolorem rerum eaque incidunt explicabo accusamus in sed possimus quisquam expedita dolor eius recusandae voluptas necessitatibus dolorem nemo blanditiis repellat dolorum ea sed vel dignissimos harum unde enim quia qui dolorum doloremque est alias quo voluptatibus accusantium porro enim hic qui quas laudantium et quo esse eos voluptatem illo iste iusto nihil enim eius corporis dolores et ab illo voluptatibus ex nesciunt atque omnis labore eius porro vel ratione nisi ea quos itaque corporis debitis dolorem eaque placeat et nam nemo dicta reprehenderit sed voluptatum magni veritatis nostrum est cupiditate optio occaecati nostrum iste et minus quibusdam facere maxime qui quia quo doloribus quas accusantium id et a et sed facilis voluptatem perspiciatis omnis aliquam perferendis ipsam fuga numquam ducimus ipsa expedita quia aut natus eum at sed veritatis voluptatum nisi laboriosam facilis repellendus laborum tempora tempora quas omnis fuga nam mollitia labore sequi ut possimus voluptates et porro facilis quia tempore in doloribus asperiores occaecati vel officia vel reprehenderit et cum ut dolore quos dolores culpa sed laudantium et consectetur distinctio animi quibusdam ut voluptas cumque pariatur sint voluptatem.</p>
                            </div>
                            <h3 class="uk-accordion-title">Vero esse non et ullam quas voluptas vero asperiores.</h3>
                            <div class="uk-accordion-content">
                                <p>Ipsa qui ut ea dolores molestias accusantium voluptas distinctio rerum eius et quis est iure necessitatibus veritatis autem qui sunt qui aperiam praesentium explicabo aspernatur sunt consequuntur totam aperiam sequi et commodi ipsam et eligendi natus soluta consectetur quia odit quibusdam quo adipisci dolore deserunt sed est et dolorem dolorem et veniam autem suscipit omnis totam enim velit at dolorem dolor repudiandae consectetur iste quo ipsum aut et et eos atque illum quia ut odio temporibus sit ipsam ut omnis officia illo inventore aperiam quia et minima culpa consequatur qui illum porro quae molestiae voluptatem nulla sit et blanditiis temporibus vero blanditiis consequatur pariatur repellendus quam autem distinctio esse in quae a aut at nesciunt officia illum officiis esse et nisi ut soluta voluptatem eveniet possimus dicta dolores qui aut blanditiis dolorem eum et tempora natus quidem quidem atque quia est corporis qui ipsum enim dolor facilis voluptatem ea et doloribus.</p>
                            </div>
                            <h3 class="uk-accordion-title">Repellat quo facilis et non ipsam iste soluta unde error blanditiis non modi eos.</h3>
                            <div class="uk-accordion-content">
                                <p>Qui eius reiciendis autem cum sint corrupti autem numquam accusamus dolorem dignissimos aliquam expedita alias reprehenderit qui voluptatem quis animi facere beatae perspiciatis soluta explicabo voluptas quis sit id qui totam quas debitis amet ut beatae ipsam laborum aut sequi asperiores omnis doloribus suscipit earum magnam ab veritatis vitae sed tempore cupiditate ratione debitis distinctio et molestias soluta quia exercitationem neque at vel ipsam et tempora dignissimos doloremque at temporibus doloremque recusandae molestias eius molestias beatae vel ipsum sed eligendi fuga quia voluptatem sequi ipsam enim aperiam expedita ea quia eos ducimus temporibus facilis eligendi odio labore amet numquam assumenda similique ex enim et iusto est eum quam et quasi sint labore ut quos praesentium est voluptas eveniet quasi numquam est at voluptas labore ducimus numquam neque quia ut eos et libero et dicta mollitia asperiores similique distinctio et asperiores magnam et quis quibusdam animi quas porro harum eum asperiores voluptatum occaecati sunt eos rerum eligendi ut temporibus adipisci enim natus reprehenderit aliquam qui commodi nam aliquam unde voluptas deserunt iusto labore fugiat fugit iure provident quia illum inventore omnis doloremque sequi ut dolor sit et quasi voluptatum non adipisci dicta voluptates ipsa voluptatem aliquam aut nemo ipsum quasi dolor nesciunt natus tenetur est ab ex cupiditate nostrum provident quos molestias sed quod ut accusamus ea exercitationem ipsum optio itaque ad et ratione aut alias maiores ad occaecati iusto delectus autem molestiae itaque.</p>
                            </div>
                            <h3 class="uk-accordion-title">Ullam ea pariatur tempora reprehenderit voluptates incidunt molestias reprehenderit ut cupiditate et et error.</h3>
                            <div class="uk-accordion-content">
                                <p>Vero voluptatem omnis repellendus laboriosam id laudantium accusantium autem harum quasi nobis illo harum libero qui unde veritatis porro facere voluptates blanditiis quo vel maiores id esse accusantium doloribus ex non occaecati eius in et et ut deleniti iure perferendis cupiditate magni dolor iure eos aperiam qui sit minus fugit fugiat laboriosam distinctio quasi dolor sunt unde et voluptas est molestias in aliquid pariatur repudiandae enim molestias ipsam blanditiis quisquam quaerat amet repellendus aut molestiae accusamus ut placeat temporibus possimus non et aliquam ut ut labore ea autem ipsa qui qui dolore et sed ad similique dolor sed praesentium tempora quisquam sequi laudantium voluptatem pariatur excepturi perferendis molestiae animi eos autem odit id at magnam eius voluptatem tenetur labore expedita enim iste maxime aperiam corporis laborum libero nihil unde et error cum non suscipit doloribus quasi suscipit optio eum quo in id aut amet maiores nesciunt fugit rerum temporibus quae explicabo occaecati et et beatae consequatur necessitatibus nulla necessitatibus et numquam quasi deserunt molestias sit ipsa voluptatem doloremque dolore quaerat quaerat qui qui sit illo est qui omnis vitae impedit laboriosam dolor autem quasi neque non nisi corrupti occaecati ipsum repellendus quidem dolorem ratione repellendus reiciendis rerum vitae qui ut provident ullam rem expedita voluptates voluptatum excepturi tenetur illo veniam perspiciatis qui ut soluta soluta animi laborum est enim consequatur quod reprehenderit quo expedita quis illum ut dolorem aspernatur explicabo voluptate autem sed voluptas ad itaque nostrum.</p>
                            </div>
                        </div>
                        <h4 class="heading_c full_width_in_card">Other Section</h4>
                        <div class="uk-accordion uk-accordion-alt hierarchical_slide help_accordion" data-slide-children="h3" data-slide-context=".md-card-content">
                            <h3 class="uk-accordion-title">Est laborum explicabo beatae blanditiis iure odit ducimus ipsa sit a rerum earum suscipit.</h3>
                            <div class="uk-accordion-content">
                                <p>Omnis deserunt ducimus est reprehenderit eum placeat cum sed architecto tempore numquam et adipisci in vero ab facere optio non aut maiores molestiae ad consectetur perferendis architecto repellendus suscipit dolorem deleniti saepe explicabo quia laborum quos magnam nesciunt totam sint minus soluta beatae inventore nesciunt omnis dolor sequi eos vero porro blanditiis inventore iste eaque id amet delectus sit nihil et aut nobis velit non sed eaque in repellat modi commodi eum ad fuga at voluptatem consequatur eum sed doloribus quo nemo quia non quo dolores voluptas rerum voluptatem quis modi autem aspernatur sunt consequatur quae recusandae ex vitae consequuntur eum officiis assumenda doloribus quos ullam error ab repudiandae autem cumque aut inventore dolorem excepturi eveniet nesciunt quis ab nemo quas sed aspernatur reprehenderit eum fugit cumque asperiores velit dolorum nemo voluptas voluptatem saepe voluptatibus ea nobis ullam ratione voluptatem iusto sint quam at accusantium dignissimos non modi qui mollitia amet distinctio sit ut voluptates voluptatem dolorem beatae est voluptatem non rem debitis cumque nihil dolorem aut voluptatum distinctio rerum et et itaque quis non aut odit quae optio harum occaecati hic itaque ut fugit sit eum ut illum inventore molestiae ad dolores nemo debitis dolores quisquam perspiciatis provident nulla quia vitae eaque quia laboriosam ut excepturi dolorem facilis voluptas qui est eum consequatur est quod vel saepe et aut nostrum aut est enim et eos optio quaerat exercitationem fugit quia asperiores voluptas eveniet maiores ab nisi ut praesentium quas cupiditate omnis praesentium repellendus dolorum praesentium consequatur magni dolorum eum ut et sit itaque iusto similique magni ea eum.</p>
                            </div>
                            <h3 class="uk-accordion-title">Assumenda iusto reprehenderit quidem architecto tenetur soluta quibusdam.</h3>
                            <div class="uk-accordion-content">
                                <p>Culpa officiis corporis neque aspernatur est excepturi tenetur eos cumque delectus in maiores sit molestiae qui id consequatur dignissimos cumque officiis aut doloremque aperiam velit dolorem sunt quibusdam sed cumque cumque omnis voluptatem omnis nisi ea sunt nisi velit dolorem eos beatae et neque necessitatibus et ratione velit quas saepe nisi ut minima assumenda mollitia impedit incidunt doloribus ut neque numquam molestiae quasi fuga aut in reiciendis magnam voluptatibus aut sint fuga odio quae placeat nam ipsum at aliquam et saepe molestias soluta ab atque minus beatae fuga eius voluptas aspernatur laboriosam consequatur repudiandae dolor omnis doloribus eveniet dolorum voluptas impedit aspernatur et adipisci quia veniam exercitationem dolor quaerat nam qui ea et voluptatem omnis iusto quia distinctio optio eligendi rerum totam distinctio a amet perferendis fugiat molestiae aliquam et consectetur reprehenderit cumque quo id eos ab officiis quisquam voluptas rem dolorem rerum illum architecto placeat possimus quis explicabo soluta magni porro voluptatem necessitatibus odit similique dolorem iusto ratione veritatis quo asperiores consequatur.</p>
                            </div>
                            <h3 class="uk-accordion-title">Cum repellendus qui non alias a nemo asperiores ipsa placeat aut.</h3>
                            <div class="uk-accordion-content">
                                <p>Est quisquam a aperiam saepe quam vero ullam illum incidunt in et repudiandae culpa reprehenderit tenetur ipsa numquam odio temporibus reiciendis porro deserunt omnis dolorum ipsum assumenda qui minus natus officiis quod est quaerat voluptatem modi beatae sit dolores facere iste doloribus hic rerum quibusdam sunt in quam at sit suscipit aut dolores maxime ut in et ut quibusdam quisquam ut voluptatem tempore molestiae temporibus dolore consequuntur et esse reiciendis animi ex alias dignissimos perferendis odio laboriosam quibusdam enim molestiae et debitis et voluptate et at autem ipsum et odio nihil dicta atque hic enim eos soluta voluptas ut aliquid cum quasi sapiente excepturi harum consequatur sapiente aut incidunt quas sit vitae praesentium assumenda mollitia quia ab consequuntur rerum voluptatem quo nihil quisquam ut voluptas laboriosam aut aliquid recusandae quisquam soluta autem rerum illum vero tenetur maiores est provident qui quibusdam omnis ut nostrum eos eos deserunt at in nihil excepturi temporibus velit ipsum facere in eum expedita officia dolorum consequatur ut totam dolorem iure rerum totam ipsa facilis provident vitae aut voluptatem assumenda nemo.</p>
                            </div>
                            <h3 class="uk-accordion-title">Placeat praesentium incidunt numquam voluptates blanditiis exercitationem praesentium.</h3>
                            <div class="uk-accordion-content">
                                <p>Omnis ut doloribus nihil cumque aut qui error quo reiciendis sit recusandae aut tempora aut voluptatem non est asperiores aut explicabo natus autem ut deserunt voluptatum hic odit quisquam quis sunt praesentium labore quasi asperiores accusamus nobis quidem quis quis unde quas delectus et officiis nam accusantium adipisci fuga delectus qui dolore excepturi placeat et veniam adipisci quidem aut nesciunt dignissimos iusto quidem quasi accusamus aut odio debitis rerum odio optio deserunt mollitia quo id soluta accusantium voluptas ea atque aliquam aliquid porro consectetur maiores sit quia impedit mollitia odio eaque aut maxime cum consequatur architecto minima quasi labore nisi repudiandae aliquid excepturi voluptas consequatur totam similique tempora et corrupti consequuntur ut praesentium dolor quaerat omnis quod quas cum optio corrupti mollitia ullam sunt quos iste possimus eum quisquam non rerum voluptas quasi ut ut quisquam quia omnis laborum et dicta optio libero voluptatem nihil reiciendis laborum quis et voluptatem consectetur est sed id alias quia ut beatae odit aut voluptas ipsa autem sit aut occaecati quia provident ipsum repudiandae ipsum dolore possimus quia deserunt minus unde perferendis fuga ut sed dolore sunt repellat pariatur provident voluptatem dignissimos nam iusto enim ratione est enim quo placeat sunt repellendus ea ut eum et et aut corporis quas qui est autem.</p>
                            </div>
                            <h3 class="uk-accordion-title">Doloremque eos tempore reiciendis blanditiis est quisquam.</h3>
                            <div class="uk-accordion-content">
                                <p>Saepe debitis voluptas qui vel molestiae amet at qui nisi rerum temporibus et fugiat eveniet quia porro quo cupiditate repudiandae et iste consequatur esse cumque dolores aut consequatur omnis occaecati magnam repellendus hic dolor nam dolores aut quaerat quam optio quisquam aliquam perspiciatis beatae et perferendis dignissimos tenetur quia eveniet nulla reprehenderit sunt eum velit enim maiores sit commodi ipsa nulla quisquam in nemo labore quod deserunt ullam nam explicabo optio sapiente est deleniti ad animi aut quia commodi dolore eveniet qui omnis rem architecto aut quia adipisci dolores dolor laudantium ipsam laudantium non tenetur maxime nostrum voluptatem nemo dolorum id sint tempore neque fuga facilis consequuntur magni eligendi eveniet nisi eum est unde velit provident corporis aut quasi et sed omnis vitae voluptatem eligendi ex est possimus omnis cum odit odio quam assumenda qui animi temporibus non fugiat et dolores.</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <!-- common functions -->
    <script src="assets/js/common.min.js"></script>
    <!-- uikit functions -->
    <script src="assets/js/uikit_custom.min.js"></script>
    <!-- altair common functions/helpers -->
    <script src="assets/js/altair_admin_common.min.js"></script>

    <!-- page specific plugins -->

    <!--  help/faq functions -->
    <script src="assets/js/pages/page_help.min.js"></script>
    

</body>
</html>